import type { Metadata } from "next";
import { ReactNode } from "react";
import { Header } from "@/shared/components/shared";

export const metadata: Metadata = {
  title: "Food Store | Home",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
  modal,
}: Readonly<{
  children: ReactNode;
  modal: ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <Header hasSearch />
      {children}
      {modal}
    </main>

  );
}
